-- Query for icd codes of sepsis and subcategories 
-- to be classified as - SEPSIS
CREATE TEMP TABLE icd_sepsis AS
SELECT *, 'sepsis' AS diagnoses_category
FROM d_icd_diagnoses
WHERE long_title LIKE '%Salmonella septicemia%'
OR long_title LIKE '%Septicemic plague%'
OR long_title LIKE '%Anthrax septicemia%'
OR long_title LIKE '%Streptococcal septicemia%'
OR long_title LIKE '%Staphylococcal septicemia, unspecified%'
OR long_title LIKE '%Methicillin susceptible Staphylococcus aureus septicemia%'
OR long_title LIKE '%Methicillin resistant Staphylococcus aureus septicemia%'
OR long_title LIKE '%Other staphylococcal septicemia%'
OR long_title LIKE '%Pneumococcal septicemia [Streptococcus pneumoniae septicemia]%'
OR long_title LIKE '%Septicemia due to anaerobes%'
OR long_title LIKE '%Septicemia due to gram-negative organism, unspecified%'
OR long_title LIKE '%Septicemia due to hemophilus influenzae [H. influenzae]%'
OR long_title LIKE '%Septicemia due to escherichia coli [E. coli]%'
OR long_title LIKE '%Septicemia due to pseudomonas%'
OR long_title LIKE '%Septicemia due to serratia%'
OR long_title LIKE '%Other septicemia due to gram-negative organisms%'
OR long_title LIKE '%Other specified septicemias%'
OR long_title LIKE '%Unspecified septicemia%'
OR long_title LIKE '%Herpetic septicemia%'
OR long_title LIKE '%Septic pulmonary embolism%'
OR long_title LIKE '%Septic myocarditis%'
OR long_title LIKE '%Septic arterial embolism%'
OR long_title LIKE '%Puerperal sepsis, unspecified as to episode of care or not applicable%'
OR long_title LIKE '%Puerperal sepsis, delivered, with mention of postpartum complication%'
OR long_title LIKE '%Puerperal sepsis, postpartum condition or complication%'
OR long_title LIKE '%Puerperal septic thrombophlebitis, unspecified as to episode of care or not applicable%'
OR long_title LIKE '%Puerperal septic thrombophlebitis, delivered, with mention of postpartum complication%'
OR long_title LIKE '%Puerperal septic thrombophlebitis, postpartum condition or complication%'
OR long_title LIKE '%Obstetrical pyemic and septic embolism, unspecified as to episode of care or not applicable%'
OR long_title LIKE '%Obstetrical pyemic and septic embolism, delivered, with or without mention of antepartum condition%'
OR long_title LIKE '%Obstetrical pyemic and septic embolism, delivered, with mention of postpartum complication%'
OR long_title LIKE '%Obstetrical pyemic and septic embolism, antepartum condition or complication%'
OR long_title LIKE '%Obstetrical pyemic and septic embolism, postpartum condition or complication%'
OR long_title LIKE '%Septicemia [sepsis] of newborn%'
OR long_title LIKE '%Septic shock%'
OR long_title LIKE '%Sepsis%'
OR long_title LIKE '%Severe sepsis%'
OR long_title LIKE '%Postoperative shock, septic%'
OR long_title LIKE '%Salmonella sepsis%'
OR long_title LIKE '%Erysipelothrix sepsis%'
OR long_title LIKE '%Listerial sepsis%'
OR long_title LIKE '%Streptococcal sepsis%'
OR long_title LIKE '%Sepsis due to streptococcus, group A%'
OR long_title LIKE '%Sepsis due to streptococcus, group B%'
OR long_title LIKE '%Sepsis due to Streptococcus pneumoniae%'
OR long_title LIKE '%Other streptococcal sepsis%'
OR long_title LIKE '%Streptococcal sepsis, unspecified%'
OR long_title LIKE '%Other sepsis%'
OR long_title LIKE '%Sepsis due to Staphylococcus aureus%'
OR long_title LIKE '%Sepsis due to Methicillin susceptible Staphylococcus aureus%'
OR long_title LIKE '%Sepsis due to Methicillin resistant Staphylococcus aureus%'
OR long_title LIKE '%Sepsis due to other specified staphylococcus%'
OR long_title LIKE '%Sepsis due to unspecified staphylococcus%'
OR long_title LIKE '%Sepsis due to Hemophilus influenzae%'
OR long_title LIKE '%Sepsis due to anaerobes%'
OR long_title LIKE '%Sepsis due to other Gram-negative organisms%'
OR long_title LIKE '%Gram-negative sepsis, unspecified%'
OR long_title LIKE '%Sepsis due to Escherichia coli [E. coli]%'
OR long_title LIKE '%Sepsis due to Pseudomonas%'
OR long_title LIKE '%Sepsis due to Serratia%'
OR long_title LIKE '%Other Gram-negative sepsis%'
OR long_title LIKE '%Other specified sepsis%'
OR long_title LIKE '%Sepsis, unspecified organism%'
OR long_title LIKE '%Actinomycotic sepsis%'
OR long_title LIKE '%Gonococcal sepsis%'
OR long_title LIKE '%Candidal sepsis%'
OR long_title LIKE '%Septic pulmonary embolism with acute cor pulmonale%'
OR long_title LIKE '%Septic pulmonary embolism without acute cor pulmonale%'
OR long_title LIKE '%Septic arterial embolism%'
OR long_title LIKE '%Sepsis following incomplete spontaneous abortion%'
OR long_title LIKE '%Sepsis following complete or unspecified spontaneous abortion%'
OR long_title LIKE '%Sepsis following (induced) termination of pregnancy%'
OR long_title LIKE '%Sepsis following failed attempted termination of pregnancy%'
OR long_title LIKE '%Sepsis following ectopic and molar pregnancy%'
OR long_title LIKE '%Puerperal sepsis%'
OR long_title LIKE '%Sepsis following an obstetrical procedure%'
OR long_title LIKE '%Puerperal septic thrombophlebitis%'
OR long_title LIKE '%Obstetric pyemic and septic embolism%'
OR long_title LIKE '%Sepsis of newborn%'
OR long_title LIKE '%Severe sepsis without septic shock%'
OR long_title LIKE '%Severe sepsis with septic shock%'
OR long_title LIKE '%Postprocedural septic shock%'
OR long_title LIKE '%Sepsis following a procedure%'
;


CREATE INDEX idx_icd_sepsis ON icd_sepsis(icd_code);
