-- Query for icd codes of Pneumonia and subcategories 
-- to be classified as - Pneumonia
CREATE TEMP TABLE icd_pneumonia AS
SELECT *, 'pneumonia' AS diagnoses_category
FROM d_icd_diagnoses
WHERE long_title LIKE '%Salmonella pneumonia%'
OR long_title LIKE '%Tuberculous pneumonia [any form], unspecified%'
OR long_title LIKE '%Tuberculous pneumonia [any form], bacteriological or histological examination not done%'
OR long_title LIKE '%Tuberculous pneumonia [any form], bacteriological or histological examination unknown (at present)%'
OR long_title LIKE '%Tuberculous pneumonia [any form], tubercle bacilli found (in sputum) by microscopy%'
OR long_title LIKE '%Tuberculous pneumonia [any form], tubercle bacilli not found (in sputum) by microscopy, but found by bacterial culture%'
OR long_title LIKE '%Tuberculous pneumonia [any form], tubercle bacilli not found by bacteriological examination, but tuberculosis confirmed histologically%'
OR long_title LIKE '%Tuberculous pneumonia [any form], tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]%'
OR long_title LIKE '%Postmeasles pneumonia%'
OR long_title LIKE '%Ornithosis with pneumonia%'
OR long_title LIKE '%Infection by Histoplasma capsulatum, pneumonia%'
OR long_title LIKE '%Infection by Histoplasma duboisii, pneumonia%'
OR long_title LIKE '%Histoplasmosis, unspecified, pneumonia%'
OR long_title LIKE '%Pneumonia due to adenovirus%'
OR long_title LIKE '%Pneumonia due to respiratory syncytial virus%'
OR long_title LIKE '%Pneumonia due to parainfluenza virus%'
OR long_title LIKE '%Pneumonia due to SARS-associated coronavirus%'
OR long_title LIKE '%Pneumonia due to other virus not elsewhere classified%'
OR long_title LIKE '%Viral pneumonia, unspecified%'
OR long_title LIKE '%Pneumococcal pneumonia [Streptococcus pneumoniae pneumonia]%'
OR long_title LIKE '%Pneumonia due to Klebsiella pneumoniae%'
OR long_title LIKE '%Pneumonia due to Pseudomonas%'
OR long_title LIKE '%Pneumonia due to Hemophilus influenzae [H. influenzae]%'
OR long_title LIKE '%Pneumonia due to Streptococcus, unspecified%'
OR long_title LIKE '%Pneumonia due to Streptococcus, group A%'
OR long_title LIKE '%Pneumonia due to Streptococcus, group B%'
OR long_title LIKE '%Pneumonia due to other Streptococcus%'
OR long_title LIKE '%Pneumonia due to Staphylococcus, unspecified%'
OR long_title LIKE '%Methicillin susceptible pneumonia due to Staphylococcus aureus%'
OR long_title LIKE '%Methicillin resistant pneumonia due to Staphylococcus aureus%'
OR long_title LIKE '%Other Staphylococcus pneumonia%'
OR long_title LIKE '%Pneumonia due to anaerobes%'
OR long_title LIKE '%Pneumonia due to escherichia coli [E. coli]%'
OR long_title LIKE '%Pneumonia due to other gram-negative bacteria%'
OR long_title LIKE '%Pneumonia due to Legionnaires disease%'
OR long_title LIKE '%Pneumonia due to other specified bacteria%'
OR long_title LIKE '%Bacterial pneumonia, unspecified%'
OR long_title LIKE '%Pneumonia due to mycoplasma pneumoniae%'
OR long_title LIKE '%Pneumonia due to chlamydia%'
OR long_title LIKE '%Pneumonia due to other specified organism%'
OR long_title LIKE '%Pneumonia in cytomegalic inclusion disease%'
OR long_title LIKE '%Pneumonia in whooping cough%'
OR long_title LIKE '%Pneumonia in anthrax%'
OR long_title LIKE '%Pneumonia in aspergillosis%'
OR long_title LIKE '%Pneumonia in other systemic mycoses%'
OR long_title LIKE '%Pneumonia in other infectious diseases classified elsewhere%'
OR long_title LIKE '%Bronchopneumonia, organism unspecified%'
OR long_title LIKE '%Pneumonia, organism unspecified%'
OR long_title LIKE '%Influenza with pneumonia%'
OR long_title LIKE '%Influenza due to identified avian influenza virus with pneumonia%'
OR long_title LIKE '%Influenza due to identified 2009 H1N1 influenza virus with pneumonia%'
OR long_title LIKE '%Influenza due to identified novel influenza A virus with pneumonia%'
OR long_title LIKE '%Idiopathic interstitial pneumonia, not otherwise specified%'
OR long_title LIKE '%Idiopathic lymphoid interstitial pneumonia%'
OR long_title LIKE '%Cryptogenic organizing pneumonia%'
OR long_title LIKE '%Desquamative interstitial pneumonia%'
OR long_title LIKE '%Rheumatic pneumonia%'
OR long_title LIKE '%Congenital pneumonia%'
OR long_title LIKE '%Ventilator associated pneumonia%'
OR long_title LIKE '%Postprocedural aspiration pneumonia%'
OR long_title LIKE '%Typhoid pneumonia%'
OR long_title LIKE '%Whooping cough due to Bordetella pertussis with pneumonia%'
OR long_title LIKE '%Whooping cough due to Bordetella parapertussis with pneumonia%'
OR long_title LIKE '%Whooping cough due to other Bordetella species with pneumonia%'
OR long_title LIKE '%Whooping cough, unspecified species with pneumonia%'
OR long_title LIKE '%Early congenital syphilitic pneumonia%'
OR long_title LIKE '%Gonococcal pneumonia%'
OR long_title LIKE '%Varicella pneumonia%'
OR long_title LIKE '%Measles complicated by pneumonia%'
OR long_title LIKE '%Rubella pneumonia%'
OR long_title LIKE '%Ascariasis pneumonia%'
OR long_title LIKE '%Influenza due to identified novel influenza A virus with pneumonia%'
OR long_title LIKE '%Influenza due to other identified influenza virus with pneumonia%'
OR long_title LIKE '%Influenza due to other identified influenza virus with unspecified type of pneumonia%'
OR long_title LIKE '%Influenza due to other identified influenza virus with the same other identified influenza virus pneumonia%'
OR long_title LIKE '%Influenza due to other identified influenza virus with other specified pneumonia%'
OR long_title LIKE '%Influenza due to unidentified influenza virus with pneumonia%'
OR long_title LIKE '%Influenza due to unidentified influenza virus with unspecified type of pneumonia%'
OR long_title LIKE '%Influenza due to unidentified influenza virus with specified pneumonia%'
OR long_title LIKE '%Viral pneumonia, not elsewhere classified%'
OR long_title LIKE '%Adenoviral pneumonia%'
OR long_title LIKE '%Respiratory syncytial virus pneumonia%'
OR long_title LIKE '%Parainfluenza virus pneumonia%'
OR long_title LIKE '%Human metapneumovirus pneumonia%'
OR long_title LIKE '%Other viral pneumonia%'
OR long_title LIKE '%Pneumonia due to SARS-associated coronavirus%'
OR long_title LIKE '%Pneumonia due to coronavirus disease 2019%'
OR long_title LIKE '%Pneumonia, unspecified organism%'
OR long_title LIKE '%Bronchopneumonia, unspecified organism%'
OR long_title LIKE '%Lobar pneumonia, unspecified organism%'
OR long_title LIKE '%Hypostatic pneumonia, unspecified organism%'
OR long_title LIKE '%Other pneumonia, unspecified organism%'
OR long_title LIKE '%Pneumonia due to Streptococcus pneumoniae%'
OR long_title LIKE '%Pneumonia due to Hemophilus influenzae%'
OR long_title LIKE '%Bacterial pneumonia, not elsewhere classified%'
OR long_title LIKE '%Pneumonia due to Klebsiella pneumoniae%'
OR long_title LIKE '%Pneumonia due to Pseudomonas%'
OR long_title LIKE '%Pneumonia due to staphylococcus%'
OR long_title LIKE '%Pneumonia due to streptococcus, group B%'
OR long_title LIKE '%Pneumonia due to other streptococci%'
OR long_title LIKE '%Pneumonia due to Escherichia coli%'
OR long_title LIKE '%Pneumonia due to other Gram-negative bacteria%'
OR long_title LIKE '%Pneumonia due to Mycoplasma pneumoniae%'
OR long_title LIKE '%Pneumonia due to other specified bacteria%'
OR long_title LIKE '%Unspecified bacterial pneumonia%'
OR long_title LIKE '%Pneumonia due to other infectious organisms, not elsewhere classified%'
OR long_title LIKE '%Chlamydial pneumonia%'
OR long_title LIKE '%Pneumonia in diseases classified elsewhere%'
OR long_title LIKE '%Pneumonia, unspecified organism%'
OR long_title LIKE '%Acute bronchitis due to Mycoplasma pneumoniae%'
OR long_title LIKE '%Chronic eosinophilic pneumonia%'
OR long_title LIKE '%Acute eosinophilic pneumonia%'
OR long_title LIKE '%Idiopathic interstitial pneumonia%'
OR long_title LIKE '%Lymphoid interstitial pneumonia%'
OR long_title LIKE '%Abscess of lung with pneumonia%'
OR long_title LIKE '%Ventilator associated pneumonia%'
OR long_title LIKE '%Congenital pneumonia%'
OR long_title LIKE '%Pyemic and septic embolism in pregnancy%'
OR long_title LIKE '%Pneumonia in pregnancy%'
;


CREATE INDEX idx_icd_pneumonia ON icd_pneumonia(icd_code);